"""
Day 5 + Day 10: Send the weekly menu, grocery list, and dashboard HTML
to the family Telegram group.

Reads latest_week_plan.json and latest_grocery_list.json (already generated by
plan_week.py and make_grocery_list.py), formats clean messages, and delivers
them. If dashboard.html exists, sends it as a downloadable file too.

Special handling: when dinner reuses lunch's dish_id, show it as "Lunch leftovers"
in the Telegram message and elevate the protein booster.
"""

import os
import json
import time
import mimetypes
import urllib.request
import urllib.parse
import urllib.error
from datetime import date, datetime
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
CHAT_ID   = os.getenv("TELEGRAM_CHAT_ID")

PLAN_FILE      = "latest_week_plan.json"
GROCERY_FILE   = "latest_grocery_list.json"
DASHBOARD_FILE = "dashboard.html"

if not BOT_TOKEN:
    raise RuntimeError("TELEGRAM_BOT_TOKEN not found in .env")
if not CHAT_ID:
    raise RuntimeError("TELEGRAM_CHAT_ID not found in .env")


# =========================================================
# File loaders
# =========================================================

def load_plan():
    with open(PLAN_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def load_grocery():
    with open(GROCERY_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def load_dish_lookup():
    """Return dict of dish_id -> dish_name from Google Sheets."""
    try:
        from load_data import get_sheet, load_tab
        sheet = get_sheet()
        dishes = load_tab(sheet, "dishes")
        return {d.get("dish_id", ""): d.get("dish_name", "") for d in dishes}
    except Exception as e:
        print(f"  ⚠️  Could not load dish lookup: {e}")
        return {}


# =========================================================
# Message formatters
# =========================================================

def format_week_message(plan, dish_lookup):
    """Build the weekly menu message. Plain text — safer than Markdown."""
    lines = []
    lines.append(f"🗓️ MENU — Week of {plan['week_starting']}")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━")

    for day in plan["days"]:
        training_tag = "  🏃‍♀️" if day.get("is_training_day") else ""
        lines.append("")
        lines.append(f"📆 {day['day_of_week']}, {day['date']}{training_tag}")

        # Breakfast
        bf = day["breakfast"]
        bf_name = bf.get("dish_name", "-")
        supp = (bf.get("supplement") or "").strip().lower()
        if supp and supp not in ("none", "null", ""):
            lines.append(f"🍳 Breakfast: {bf_name} + {supp}")
        else:
            lines.append(f"🍳 Breakfast: {bf_name}")

        # Lunch
        lunch_id = day["lunch"].get("dish_id", "")
        lunch_name = day["lunch"].get("dish_name", "-")
        lines.append(f"🍛 Lunch:     {lunch_name}")

        # Dinner (leftovers vs distinct)
        dinner_id = day["dinner"].get("dish_id", "")
        dinner_name = day["dinner"].get("dish_name", "-")
        is_leftovers = lunch_id and dinner_id and (lunch_id == dinner_id)
        if is_leftovers:
            lines.append(f"🍽️ Dinner:    Lunch leftovers (reheat)")
        else:
            lines.append(f"🍽️ Dinner:    {dinner_name}")

        # Protein booster — always resolve to real dish name
        booster_id = day["dinner"].get("protein_booster_dish_id")
        if booster_id and str(booster_id).lower() not in ("null", "none", ""):
            booster_name = dish_lookup.get(booster_id, booster_id)
            if day.get("is_training_day"):
                lines.append(f"   🥩 Extra protein tonight: {booster_name}")
            else:
                lines.append(f"   💪 Additional high-protein option: {booster_name}")

        fruit = day.get("fruit_of_the_day", "-")
        lines.append(f"🍎 Fruit: {fruit}")

    lines.append("")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("Reply with:")
    lines.append("• 'ok' to confirm this week")
    lines.append("• 'change [day] [meal] to [dish]' to edit")

    return "\n".join(lines)


def format_grocery_message(grocery):
    lines = []
    lines.append(f"🛒 GROCERY LIST — Week of {grocery['week_starting']}")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━")

    sections = [
        ("🥫 SUNDAY — Pantry & dry goods", "sunday_pantry"),
        ("🥦 WEDNESDAY — Fresh veg & herbs", "wednesday_fresh_veg"),
        ("🍗 FRIDAY — Meat, eggs, paneer", "friday_perishables"),
    ]

    for header, key in sections:
        items = grocery.get(key, [])
        lines.append("")
        lines.append(header)
        lines.append("─" * 24)
        if not items:
            lines.append("  (no items)")
            continue
        for item in items:
            name = item.get("item", "?")
            qty = item.get("quantity", "?")
            lines.append(f"  • {name}: {qty}")

    notes = grocery.get("notes", "")
    if notes:
        lines.append("")
        lines.append(f"📝 {notes}")

    return "\n".join(lines)


# =========================================================
# Telegram senders
# =========================================================

def send_message(text):
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    data = urllib.parse.urlencode({
        "chat_id": CHAT_ID,
        "text": text,
        "disable_web_page_preview": "true",
    }).encode("utf-8")

    req = urllib.request.Request(url, data=data, method="POST")
    try:
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode("utf-8"))
            if not result.get("ok"):
                raise RuntimeError(f"Telegram API error: {result}")
            return result
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        raise RuntimeError(f"HTTP {e.code} from Telegram: {error_body}")


def send_document(file_path, caption=""):
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendDocument"
    boundary = "----MenuAgentBoundary"
    filename = os.path.basename(file_path)

    with open(file_path, "rb") as f:
        file_bytes = f.read()

    mime, _ = mimetypes.guess_type(file_path)
    mime = mime or "application/octet-stream"

    body_parts = []
    body_parts.append(f"--{boundary}".encode("utf-8"))
    body_parts.append(b'Content-Disposition: form-data; name="chat_id"')
    body_parts.append(b"")
    body_parts.append(str(CHAT_ID).encode("utf-8"))

    if caption:
        body_parts.append(f"--{boundary}".encode("utf-8"))
        body_parts.append(b'Content-Disposition: form-data; name="caption"')
        body_parts.append(b"")
        body_parts.append(caption.encode("utf-8"))

    body_parts.append(f"--{boundary}".encode("utf-8"))
    body_parts.append(
        f'Content-Disposition: form-data; name="document"; filename="{filename}"'
        .encode("utf-8")
    )
    body_parts.append(f"Content-Type: {mime}".encode("utf-8"))
    body_parts.append(b"")
    body_parts.append(file_bytes)
    body_parts.append(f"--{boundary}--".encode("utf-8"))

    body = b"\r\n".join(body_parts)

    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")

    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            if not result.get("ok"):
                raise RuntimeError(f"Telegram API error: {result}")
            return result
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        raise RuntimeError(f"HTTP {e.code} from Telegram: {error_body}")


# =========================================================
# Main
# =========================================================

def main():
    print("Loading week plan and grocery list...")
    plan = load_plan()
    grocery = load_grocery()
    dish_lookup = load_dish_lookup()

    print(f"  - Plan: {len(plan['days'])} days")
    total_grocery = sum(
        len(grocery.get(k, []))
        for k in ["sunday_pantry", "wednesday_fresh_veg", "friday_perishables"]
    )
    print(f"  - Grocery: {total_grocery} items across 3 buy-days")
    print(f"  - Dish lookup: {len(dish_lookup)} dishes\n")

    print("Formatting messages...")
    menu_msg = format_week_message(plan, dish_lookup)
    grocery_msg = format_grocery_message(grocery)

    print(f"  - Menu message:    {len(menu_msg)} chars")
    print(f"  - Grocery message: {len(grocery_msg)} chars\n")

    if len(menu_msg) > 4000:
        print("  ⚠️  Menu message near 4000 char limit — Telegram may truncate")
    if len(grocery_msg) > 4000:
        print("  ⚠️  Grocery message near 4000 char limit")

    print("Sending menu message to Telegram...")
    send_message(menu_msg)
    print("  ✅ Menu sent")

    time.sleep(1)

    print("Sending grocery list to Telegram...")
    send_message(grocery_msg)
    print("  ✅ Grocery list sent")

    if os.path.exists(DASHBOARD_FILE):
        print("Sending dashboard file...")
        try:
            send_document(
                DASHBOARD_FILE,
                caption="🎨 Tap to open the week dashboard in your browser"
            )
            print("  ✅ Dashboard sent")
        except Exception as e:
            print(f"  ⚠️  Failed to send dashboard: {e}")
    else:
        print("  ℹ️  No dashboard.html to send (run render_dashboard.py first)")

    print("\n🎉 All messages delivered.")


if __name__ == "__main__":
    main()