"""
Day 5: Send the weekly menu plan and grocery list to the Telegram family group.

Reads latest_week_plan.json and latest_grocery_list.json (already generated by
plan_week.py and make_grocery_list.py) and sends nicely formatted messages.

Telegram MarkdownV2 has strict escaping rules — this script handles those.
"""

import os
import json
import time
import urllib.request
import urllib.parse
from datetime import date, datetime
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

PLAN_FILE = "latest_week_plan.json"
GROCERY_FILE = "latest_grocery_list.json"

if not BOT_TOKEN:
    raise RuntimeError("TELEGRAM_BOT_TOKEN not found in .env")
if not CHAT_ID:
    raise RuntimeError("TELEGRAM_CHAT_ID not found in .env")


def load_plan():
    with open(PLAN_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def load_grocery():
    with open(GROCERY_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def format_week_message(plan):
    """Build the weekly menu message. Uses plain text - safer than Markdown."""
    lines = []
    lines.append(f"🗓️ MENU — Week of {plan['week_starting']}")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━")

    for day in plan["days"]:
        training_tag = "  🏃‍♀️" if day.get("is_training_day") else ""
        lines.append("")
        lines.append(f"📆 {day['day_of_week']}, {day['date']}{training_tag}")

        bf = day["breakfast"]
        bf_name = bf.get("dish_name", "-")
        supp = (bf.get("supplement") or "").strip().lower()
        if supp and supp not in ("none", "null", ""):
            lines.append(f"🍳 Breakfast: {bf_name} + {supp}")
        else:
            lines.append(f"🍳 Breakfast: {bf_name}")

        lines.append(f"🍛 Lunch:     {day['lunch'].get('dish_name', '-')}")
        lines.append(f"🍽️ Dinner:    {day['dinner'].get('dish_name', '-')}")

        booster_id = day["dinner"].get("protein_booster_dish_id")
        if booster_id and str(booster_id).lower() not in ("null", "none", ""):
            # Look up name from plan if available (we saved dish_name in day dict)
            # Fallback: just show the ID
            lines.append(f"   💪 Protein booster: {booster_id}")

        fruit = day.get("fruit_of_the_day", "-")
        lines.append(f"🍎 Fruit: {fruit}")

    lines.append("")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("Reply with:")
    lines.append("• 'ok' to confirm this week")
    lines.append("• 'change [day] [meal] to [dish]' to edit")

    return "\n".join(lines)


def format_grocery_message(grocery):
    """Build the grocery list message."""
    lines = []
    lines.append(f"🛒 GROCERY LIST — Week of {grocery['week_starting']}")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━")

    sections = [
        ("🥫 SUNDAY — Pantry & dry goods", "sunday_pantry"),
        ("🥦 WEDNESDAY — Fresh veg & herbs", "wednesday_fresh_veg"),
        ("🍗 FRIDAY — Meat, eggs, paneer", "friday_perishables"),
    ]

    for header, key in sections:
        items = grocery.get(key, [])
        lines.append("")
        lines.append(header)
        lines.append("─" * 24)
        if not items:
            lines.append("  (no items)")
            continue
        for item in items:
            name = item.get("item", "?")
            qty = item.get("quantity", "?")
            lines.append(f"  • {name}: {qty}")

    notes = grocery.get("notes", "")
    if notes:
        lines.append("")
        lines.append(f"📝 {notes}")

    return "\n".join(lines)


def send_message(text):
    """Send a message to the Telegram chat via HTTP API."""
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    data = urllib.parse.urlencode({
        "chat_id": CHAT_ID,
        "text": text,
        "disable_web_page_preview": "true",
    }).encode("utf-8")

    req = urllib.request.Request(url, data=data, method="POST")
    try:
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode("utf-8"))
            if not result.get("ok"):
                raise RuntimeError(f"Telegram API error: {result}")
            return result
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        raise RuntimeError(f"HTTP {e.code} from Telegram: {error_body}")


def main():
    print("Loading week plan and grocery list...")
    plan = load_plan()
    grocery = load_grocery()
    print(f"  - Plan: {len(plan['days'])} days")
    print(f"  - Grocery: {sum(len(grocery.get(k, [])) for k in ['sunday_pantry', 'wednesday_fresh_veg', 'friday_perishables'])} items across 3 buy-days\n")

    print("Formatting messages...")
    menu_msg = format_week_message(plan)
    grocery_msg = format_grocery_message(grocery)

    print(f"  - Menu message: {len(menu_msg)} chars")
    print(f"  - Grocery message: {len(grocery_msg)} chars\n")

    # Telegram allows up to 4096 chars per message. If we're over, we could split
    # but ~2000 char messages are the norm here.
    if len(menu_msg) > 4000:
        print("  ⚠️  Menu message near 4000 char limit — Telegram may truncate")
    if len(grocery_msg) > 4000:
        print("  ⚠️  Grocery message near 4000 char limit")

    print("Sending menu message to Telegram...")
    send_message(menu_msg)
    print("  ✅ Menu sent")

    # Small pause between messages so they arrive in order
    time.sleep(1)

    print("Sending grocery list to Telegram...")
    send_message(grocery_msg)
    print("  ✅ Grocery list sent")

    print("\n🎉 Both messages delivered. Check your Telegram group.")


if __name__ == "__main__":
    main()